#!/bin/bash
set -eux

os-svc-daemon ironic-conductor ironic ironic-conductor "--debug --verbose --log-config /etc/ironic/logging-conductor.conf --config-file /etc/ironic/ironic.conf"

os-svc-daemon ironic-api ironic ironic-api "--debug --verbose --log-config /etc/ironic/logging-api.conf --config-file /etc/ironic/ironic.conf"
