#!/bin/bash
set -eux

# ironic requires numpy which seems to fail installing via pip.
# including subversion to clean up a "not found" error while installing
install-packages subversion libatlas-base-dev gfortran gfortran-multilib

os-svc-install -n ironic \
    -u ironic \
    -r https://github.com/openstack/ironic.git

